### ISSUE TITLE
Deleting Outliers

### ISSUE THREAD

**Issue by SolvayB** [Navy-Precision-Optial-Interferometer/PYBOC#12] opened 2021-09-13 04:23 UTC
For some star logs, I noticed that we have outlier values for baseline offsets. Would it be possible to take the distribution of offset values for each baseline and take out whatever outliers may exist outside a certain sigma value? If you need clarification please let me know! :)

**Comment by ermaier** [comment] 2021-10-05 06:10
Closing as duplicate of  #8. See that issue for updates.

**Closed by ermaier** 2021-10-05 06:10 UTC
